### ISSUE TITLE
ImportError: cannot import name 'GridBasedHashTable_Key' from 'threestudio.utils.hash_table'

### ISSUE THREAD

**Issue by jclarkk** [Adamdad/hash3D#1]
Seems like the GridBasedHashTable_Key is missing

Also, had to manually add the 'zero123_unified_guidance_cache' into threestudio/guidance/__init__.py.

**Comment by Adamdad** [comment]
WOW, Thank you for the reminder. Will clean it up right now. 🙏

**Comment by jclarkk** [comment]
Thanks for the prompt response!

**Comment by Adamdad** [comment]
fixed. Thanks
