### ISSUE TITLE
No file here *https://adamdad.github.io/hash3D/load/images/dog1_rgba.png*

### ISSUE THREAD

**Issue by altava-sgp** [Adamdad/hash3D#4]
We can't use this file.
https://adamdad.github.io/hash3D/load/images/dog1_rgba.png

You have to contain this image to source code.
![dog1_rgba](https://github.com/Adamdad/hash3D/assets/133635323/0f598c01-e378-41c4-bdd0-9c17744b506d)

**Comment by Adamdad** [comment]
Thanks.
You can select whichever image and upload to your sever, as long as you specify its path in the code.
